// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	define "BsmgRefactoring/define"

	mock "github.com/stretchr/testify/mock"
)

// BsmgRepository is an autogenerated mock type for the BsmgRepository type
type BsmgRepository struct {
	mock.Mock
}

// SelectUserList provides a mock function with given fields:
func (_m *BsmgRepository) SelectUserList() ([]define.BsmgMemberInfo, error) {
	ret := _m.Called()

	var r0 []define.BsmgMemberInfo
	if rf, ok := ret.Get(0).(func() []define.BsmgMemberInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgMemberInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
