// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	define "BsmgRefactoring/define"

	mock "github.com/stretchr/testify/mock"
)

// DBInterface is an autogenerated mock type for the DBInterface type
type DBInterface struct {
	mock.Mock
}

// CheckMemberIDDuplicate provides a mock function with given fields: memID
func (_m *DBInterface) CheckMemberIDDuplicate(memID string) (bool, error) {
	ret := _m.Called(memID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(memID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(memID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfirmRpt provides a mock function with given fields: rptIdx
func (_m *DBInterface) ConfirmRpt(rptIdx int32) error {
	ret := _m.Called(rptIdx)

	var r0 error
	if rf, ok := ret.Get(0).(func(int32) error); ok {
		r0 = rf(rptIdx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectBSMG provides a mock function with given fields:
func (_m *DBInterface) ConnectBSMG() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectMariaDB provides a mock function with given fields:
func (_m *DBInterface) ConnectMariaDB() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAttr1Table provides a mock function with given fields:
func (_m *DBInterface) CreateAttr1Table() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAttr2Table provides a mock function with given fields:
func (_m *DBInterface) CreateAttr2Table() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateDailyReportTable provides a mock function with given fields:
func (_m *DBInterface) CreateDailyReportTable() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateDataBase provides a mock function with given fields:
func (_m *DBInterface) CreateDataBase() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMemberTable provides a mock function with given fields:
func (_m *DBInterface) CreateMemberTable() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePartTable provides a mock function with given fields:
func (_m *DBInterface) CreatePartTable() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRankTable provides a mock function with given fields:
func (_m *DBInterface) CreateRankTable() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateScheduleTable provides a mock function with given fields:
func (_m *DBInterface) CreateScheduleTable() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWeekReportTable provides a mock function with given fields:
func (_m *DBInterface) CreateWeekReportTable() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMember provides a mock function with given fields: memId
func (_m *DBInterface) DeleteMember(memId string) error {
	ret := _m.Called(memId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(memId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteReport provides a mock function with given fields: rptIdx
func (_m *DBInterface) DeleteReport(rptIdx int32) error {
	ret := _m.Called(rptIdx)

	var r0 error
	if rf, ok := ret.Get(0).(func(int32) error); ok {
		r0 = rf(rptIdx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSchedule provides a mock function with given fields: rptIdx
func (_m *DBInterface) DeleteSchedule(rptIdx int32) error {
	ret := _m.Called(rptIdx)

	var r0 error
	if rf, ok := ret.Get(0).(func(int32) error); ok {
		r0 = rf(rptIdx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWeekReport provides a mock function with given fields: wRptIdx
func (_m *DBInterface) DeleteWeekReport(wRptIdx int) error {
	ret := _m.Called(wRptIdx)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(wRptIdx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMinIdx provides a mock function with given fields:
func (_m *DBInterface) FindMinIdx() int32 {
	ret := _m.Called()

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// InsertDailyReport provides a mock function with given fields: report
func (_m *DBInterface) InsertDailyReport(report define.BsmgReportInfo) error {
	ret := _m.Called(report)

	var r0 error
	if rf, ok := ret.Get(0).(func(define.BsmgReportInfo) error); ok {
		r0 = rf(report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertDefaultAttr1 provides a mock function with given fields:
func (_m *DBInterface) InsertDefaultAttr1() {
	_m.Called()
}

// InsertDefaultAttr2 provides a mock function with given fields:
func (_m *DBInterface) InsertDefaultAttr2() {
	_m.Called()
}

// InsertDefaultPart provides a mock function with given fields:
func (_m *DBInterface) InsertDefaultPart() {
	_m.Called()
}

// InsertDefaultRank provides a mock function with given fields:
func (_m *DBInterface) InsertDefaultRank() {
	_m.Called()
}

// InsertMember provides a mock function with given fields: member
func (_m *DBInterface) InsertMember(member define.BsmgMemberInfo) error {
	ret := _m.Called(member)

	var r0 error
	if rf, ok := ret.Get(0).(func(define.BsmgMemberInfo) error); ok {
		r0 = rf(member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertSchedule provides a mock function with given fields: schedule
func (_m *DBInterface) InsertSchedule(schedule define.BsmgScheduleInfo) error {
	ret := _m.Called(schedule)

	var r0 error
	if rf, ok := ret.Get(0).(func(define.BsmgScheduleInfo) error); ok {
		r0 = rf(schedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertWeekReport provides a mock function with given fields: wRptInfo
func (_m *DBInterface) InsertWeekReport(wRptInfo define.BsmgWeekRptInfo) error {
	ret := _m.Called(wRptInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(define.BsmgWeekRptInfo) error); ok {
		r0 = rf(wRptInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsConnected provides a mock function with given fields:
func (_m *DBInterface) IsConnected() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsExistBSMG provides a mock function with given fields:
func (_m *DBInterface) IsExistBSMG() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MakeAttrTree provides a mock function with given fields:
func (_m *DBInterface) MakeAttrTree() ([]define.AttrTree, error) {
	ret := _m.Called()

	var r0 []define.AttrTree
	if rf, ok := ret.Get(0).(func() []define.AttrTree); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.AttrTree)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakePartTree provides a mock function with given fields:
func (_m *DBInterface) MakePartTree() ([]define.PartTree, error) {
	ret := _m.Called()

	var r0 []define.PartTree
	if rf, ok := ret.Get(0).(func() []define.PartTree); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.PartTree)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Release provides a mock function with given fields:
func (_m *DBInterface) Release() {
	_m.Called()
}

// SelecAttrSearchReportList provides a mock function with given fields: pageInfo, attrData
func (_m *DBInterface) SelecAttrSearchReportList(pageInfo define.PageInfo, attrData define.AttrSearchData) ([]define.BsmgReportInfoForWeb, int32, error) {
	ret := _m.Called(pageInfo, attrData)

	var r0 []define.BsmgReportInfoForWeb
	if rf, ok := ret.Get(0).(func(define.PageInfo, define.AttrSearchData) []define.BsmgReportInfoForWeb); ok {
		r0 = rf(pageInfo, attrData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgReportInfoForWeb)
		}
	}

	var r1 int32
	if rf, ok := ret.Get(1).(func(define.PageInfo, define.AttrSearchData) int32); ok {
		r1 = rf(pageInfo, attrData)
	} else {
		r1 = ret.Get(1).(int32)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(define.PageInfo, define.AttrSearchData) error); ok {
		r2 = rf(pageInfo, attrData)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SelectAttr1List provides a mock function with given fields:
func (_m *DBInterface) SelectAttr1List() ([]define.BsmgAttr1Info, error) {
	ret := _m.Called()

	var r0 []define.BsmgAttr1Info
	if rf, ok := ret.Get(0).(func() []define.BsmgAttr1Info); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgAttr1Info)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectLatestRptIdx provides a mock function with given fields: reporter
func (_m *DBInterface) SelectLatestRptIdx(reporter string) (int32, error) {
	ret := _m.Called(reporter)

	var r0 int32
	if rf, ok := ret.Get(0).(func(string) int32); ok {
		r0 = rf(reporter)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(reporter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectMemberInfo provides a mock function with given fields: member
func (_m *DBInterface) SelectMemberInfo(member *define.BsmgMemberInfo) error {
	ret := _m.Called(member)

	var r0 error
	if rf, ok := ret.Get(0).(func(*define.BsmgMemberInfo) error); ok {
		r0 = rf(member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectMemberListSearch provides a mock function with given fields: searchData
func (_m *DBInterface) SelectMemberListSearch(searchData define.SearchData) ([]define.BsmgMemberInfo, error) {
	ret := _m.Called(searchData)

	var r0 []define.BsmgMemberInfo
	if rf, ok := ret.Get(0).(func(define.SearchData) []define.BsmgMemberInfo); ok {
		r0 = rf(searchData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgMemberInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(define.SearchData) error); ok {
		r1 = rf(searchData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectPartLeader provides a mock function with given fields: Mem_Part
func (_m *DBInterface) SelectPartLeader(Mem_Part int32) (string, error) {
	ret := _m.Called(Mem_Part)

	var r0 string
	if rf, ok := ret.Get(0).(func(int32) string); ok {
		r0 = rf(Mem_Part)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int32) error); ok {
		r1 = rf(Mem_Part)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectPartist provides a mock function with given fields:
func (_m *DBInterface) SelectPartist() ([]define.BsmgPartInfo, error) {
	ret := _m.Called()

	var r0 []define.BsmgPartInfo
	if rf, ok := ret.Get(0).(func() []define.BsmgPartInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgPartInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectRankList provides a mock function with given fields:
func (_m *DBInterface) SelectRankList() ([]define.BsmgRankInfo, error) {
	ret := _m.Called()

	var r0 []define.BsmgRankInfo
	if rf, ok := ret.Get(0).(func() []define.BsmgRankInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgRankInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectReportInfo provides a mock function with given fields: idx
func (_m *DBInterface) SelectReportInfo(idx int) (define.BsmgReportInfoForWeb, error) {
	ret := _m.Called(idx)

	var r0 define.BsmgReportInfoForWeb
	if rf, ok := ret.Get(0).(func(int) define.BsmgReportInfoForWeb); ok {
		r0 = rf(idx)
	} else {
		r0 = ret.Get(0).(define.BsmgReportInfoForWeb)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectReportList provides a mock function with given fields: pageInfo, searchData
func (_m *DBInterface) SelectReportList(pageInfo define.PageInfo, searchData define.SearchData) ([]define.BsmgReportInfoForWeb, int32, error) {
	ret := _m.Called(pageInfo, searchData)

	var r0 []define.BsmgReportInfoForWeb
	if rf, ok := ret.Get(0).(func(define.PageInfo, define.SearchData) []define.BsmgReportInfoForWeb); ok {
		r0 = rf(pageInfo, searchData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgReportInfoForWeb)
		}
	}

	var r1 int32
	if rf, ok := ret.Get(1).(func(define.PageInfo, define.SearchData) int32); ok {
		r1 = rf(pageInfo, searchData)
	} else {
		r1 = ret.Get(1).(int32)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(define.PageInfo, define.SearchData) error); ok {
		r2 = rf(pageInfo, searchData)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SelectReportListAWeek provides a mock function with given fields: Mem_ID, bef7d, bef1d
func (_m *DBInterface) SelectReportListAWeek(Mem_ID string, bef7d string, bef1d string) ([]define.BsmgReportInfo, error) {
	ret := _m.Called(Mem_ID, bef7d, bef1d)

	var r0 []define.BsmgReportInfo
	if rf, ok := ret.Get(0).(func(string, string, string) []define.BsmgReportInfo); ok {
		r0 = rf(Mem_ID, bef7d, bef1d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgReportInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(Mem_ID, bef7d, bef1d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectScheduleList provides a mock function with given fields: rptIdx
func (_m *DBInterface) SelectScheduleList(rptIdx int32) ([]define.BsmgScheduleInfo, error) {
	ret := _m.Called(rptIdx)

	var r0 []define.BsmgScheduleInfo
	if rf, ok := ret.Get(0).(func(int32) []define.BsmgScheduleInfo); ok {
		r0 = rf(rptIdx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgScheduleInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int32) error); ok {
		r1 = rf(rptIdx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectUserList provides a mock function with given fields:
func (_m *DBInterface) SelectUserList() ([]define.BsmgMemberInfo, error) {
	ret := _m.Called()

	var r0 []define.BsmgMemberInfo
	if rf, ok := ret.Get(0).(func() []define.BsmgMemberInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgMemberInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectWeekReportCategorySearch provides a mock function with given fields: pageInfo, partIdx
func (_m *DBInterface) SelectWeekReportCategorySearch(pageInfo define.PageInfo, partIdx int) ([]define.BsmgWeekRptInfoForWeb, int32, error) {
	ret := _m.Called(pageInfo, partIdx)

	var r0 []define.BsmgWeekRptInfoForWeb
	if rf, ok := ret.Get(0).(func(define.PageInfo, int) []define.BsmgWeekRptInfoForWeb); ok {
		r0 = rf(pageInfo, partIdx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgWeekRptInfoForWeb)
		}
	}

	var r1 int32
	if rf, ok := ret.Get(1).(func(define.PageInfo, int) int32); ok {
		r1 = rf(pageInfo, partIdx)
	} else {
		r1 = ret.Get(1).(int32)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(define.PageInfo, int) error); ok {
		r2 = rf(pageInfo, partIdx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SelectWeekReportInfo provides a mock function with given fields: wRptIdx
func (_m *DBInterface) SelectWeekReportInfo(wRptIdx int) (define.BsmgWeekRptInfoForWeb, error) {
	ret := _m.Called(wRptIdx)

	var r0 define.BsmgWeekRptInfoForWeb
	if rf, ok := ret.Get(0).(func(int) define.BsmgWeekRptInfoForWeb); ok {
		r0 = rf(wRptIdx)
	} else {
		r0 = ret.Get(0).(define.BsmgWeekRptInfoForWeb)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(wRptIdx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectWeekReportList provides a mock function with given fields: pageInfo, searchData
func (_m *DBInterface) SelectWeekReportList(pageInfo define.PageInfo, searchData define.SearchData) ([]define.BsmgWeekRptInfoForWeb, int32, error) {
	ret := _m.Called(pageInfo, searchData)

	var r0 []define.BsmgWeekRptInfoForWeb
	if rf, ok := ret.Get(0).(func(define.PageInfo, define.SearchData) []define.BsmgWeekRptInfoForWeb); ok {
		r0 = rf(pageInfo, searchData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]define.BsmgWeekRptInfoForWeb)
		}
	}

	var r1 int32
	if rf, ok := ret.Get(1).(func(define.PageInfo, define.SearchData) int32); ok {
		r1 = rf(pageInfo, searchData)
	} else {
		r1 = ret.Get(1).(int32)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(define.PageInfo, define.SearchData) error); ok {
		r2 = rf(pageInfo, searchData)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateReportInfo provides a mock function with given fields: report
func (_m *DBInterface) UpdateReportInfo(report define.BsmgReportInfo) error {
	ret := _m.Called(report)

	var r0 error
	if rf, ok := ret.Get(0).(func(define.BsmgReportInfo) error); ok {
		r0 = rf(report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: member
func (_m *DBInterface) UpdateUser(member define.BsmgMemberInfo) error {
	ret := _m.Called(member)

	var r0 error
	if rf, ok := ret.Get(0).(func(define.BsmgMemberInfo) error); ok {
		r0 = rf(member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWeekReportInfo provides a mock function with given fields: report
func (_m *DBInterface) UpdateWeekReportInfo(report define.BsmgWeekRptInfo) error {
	ret := _m.Called(report)

	var r0 error
	if rf, ok := ret.Get(0).(func(define.BsmgWeekRptInfo) error); ok {
		r0 = rf(report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
