version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    # build:
    #   context: .
    image: web # cloud에서 이미지 빌드하고 사용 (CPU 아키텍쳐문제)
    container_name: bsmg
    # ports:
    #   - "8080:3000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: bsmgDB
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
    command:
          - --default-authentication-plugin=mysql_native_password
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
          - --skip-character-set-client-handshake
          - --max_allowed_packet=256M
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
