/**
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
cpr.I18N.INSTANCE.setLocaleData("ko", {
  "gretting": "안녕하세요, eXbuilder6!"
});
cpr.I18N.INSTANCE.setLocaleData("en", {
  "gretting": "Hello, eXbuilder6!"
});
